MAX_TEXT_LENGTH: 128
VOCAB: ./datasets/captions_vocab_coco.pickle
LANGUAGE_ENCODER: ./datasets/text_encoder_coco.pth
IMAGE_ENCODER: ./datasets/image_encoder_coco.pth

CAPTION: ./datasets/coco/caption.json